# Generated by Django 5.1.7 on 2025-05-07 03:49

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=2)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('direccion', models.TextField()),
                ('municipio', models.CharField(max_length=100)),
                ('barrio', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(max_length=15)),
                ('grado_solicitado', models.CharField(choices=[('00', 'Transición'), ('01', 'Primero'), ('02', 'Segundo'), ('03', 'Tercero'), ('04', 'Cuarto'), ('05', 'Quinto')], max_length=2)),
                ('estatus', models.CharField(choices=[('NUEVO', 'Nuevo'), ('REPITENTE', 'Repitente')], default='NUEVO', max_length=10)),
                ('nombre_acudiente', models.CharField(max_length=100)),
                ('telefono_acudiente', models.CharField(max_length=15)),
                ('email_acudiente', models.EmailField(max_length=254)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10)),
                ('fecha_aplicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aplicantes',
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=45, unique=True)),
                ('jornada', models.CharField(max_length=6)),
                ('cantidad_alumnos', models.IntegerField()),
            ],
            options={
                'db_table': 'cursos',
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'departamentos',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('documento', models.CharField(max_length=20, unique=True, verbose_name='Documento')),
                ('rol', models.CharField(choices=[('EST', 'Estudiante'), ('DOC', 'Docente'), ('ADM', 'Administrador')], default='EST', max_length=3)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DatosExtraAplicante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_padre', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_padre', models.CharField(blank=True, max_length=15, null=True)),
                ('nombre_madre', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_madre', models.CharField(blank=True, max_length=15, null=True)),
                ('contacto_emergencia', models.CharField(max_length=100)),
                ('telefono_emergencia', models.CharField(max_length=15)),
                ('eps', models.CharField(blank=True, max_length=100, null=True)),
                ('ips', models.CharField(blank=True, max_length=100, null=True)),
                ('familias_accion', models.BooleanField(default=False)),
                ('discapacidad', models.BooleanField(default=False)),
                ('tipo_discapacidad', models.CharField(blank=True, max_length=100, null=True)),
                ('aplicante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_extra', to='lms_celestin.aplicante')),
            ],
            options={
                'db_table': 'datos_extra_aplicantes',
            },
        ),
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=100)),
                ('titulos', models.TextField(blank=True, null=True)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'docentes',
            },
        ),
        migrations.CreateModel(
            name='Asignaturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('cantidad_horas', models.IntegerField()),
                ('id_docente', models.ForeignKey(db_column='id_docente', on_delete=django.db.models.deletion.CASCADE, to='lms_celestin.docentes')),
            ],
            options={
                'db_table': 'asignaturas',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_estudiante', models.CharField(max_length=20, unique=True)),
                ('grado', models.CharField(choices=[('00', 'Transición'), ('01', 'Primero'), ('02', 'Segundo'), ('03', 'Tercero'), ('04', 'Cuarto'), ('05', 'Quinto')], max_length=2)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('RETIRADO', 'Retirado')], default='ACTIVO', max_length=10)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=4)),
                ('primer_parcial', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('segundo_parcial', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('tercer_parcial', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('fecha_calificacion_primer_parcial', models.DateField(blank=True, null=True)),
                ('fecha_calificacion_segundo_parcial', models.DateField(blank=True, null=True)),
                ('fecha_calificacion_tercer_parcial', models.DateField(blank=True, null=True)),
                ('id_alumno', models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.CASCADE, to='lms_celestin.estudiante')),
            ],
            options={
                'db_table': 'calificaciones',
            },
        ),
        migrations.CreateModel(
            name='BancoLogros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('analisis', models.CharField(max_length=255)),
                ('id_alumno', models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.CASCADE, to='lms_celestin.estudiante')),
            ],
            options={
                'db_table': 'banco_logros',
            },
        ),
        migrations.CreateModel(
            name='FichaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eps', models.CharField(blank=True, max_length=100, null=True)),
                ('ips', models.CharField(blank=True, max_length=100, null=True)),
                ('sisben', models.BooleanField(default=False)),
                ('familias_accion', models.BooleanField(default=False)),
                ('discapacidad', models.BooleanField(default=False)),
                ('tipo_discapacidad', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_padre', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_padre', models.CharField(blank=True, max_length=15, null=True)),
                ('nombre_madre', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_madre', models.CharField(blank=True, max_length=15, null=True)),
                ('contacto_emergencia', models.CharField(max_length=100)),
                ('telefono_emergencia', models.CharField(max_length=15)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha', to='lms_celestin.estudiante')),
            ],
            options={
                'db_table': 'fichas_estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Matriculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_matricula', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('grado', models.CharField(max_length=20)),
                ('anio_academico', models.IntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_alumno', models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.CASCADE, to='lms_celestin.estudiante')),
            ],
            options={
                'db_table': 'matriculas',
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('id_departamento', models.ForeignKey(db_column='id_departamento', on_delete=django.db.models.deletion.CASCADE, to='lms_celestin.departamentos')),
            ],
            options={
                'db_table': 'municipios',
            },
        ),
        migrations.CreateModel(
            name='Observadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('anotacion', models.CharField(max_length=255)),
                ('id_alumno', models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.CASCADE, to='lms_celestin.estudiante')),
            ],
            options={
                'db_table': 'observadores',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('RC', 'Registro Civil'), ('TI', 'Tarjeta de Identidad'), ('CC', 'Cédula de Ciudadanía')], max_length=2)),
                ('documento', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Solo números permitidos')])),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('direccion', models.TextField()),
                ('municipio', models.CharField(max_length=100)),
                ('barrio', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'Requiere 10 dígitos')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'personas',
                'indexes': [models.Index(fields=['documento'], name='personas_documen_bdd61d_idx'), models.Index(fields=['primer_apellido', 'primer_nombre'], name='personas_primer__ff723f_idx')],
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to='lms_celestin.persona'),
        ),
        migrations.AddField(
            model_name='docentes',
            name='id_persona',
            field=models.OneToOneField(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, to='lms_celestin.persona'),
        ),
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to=settings.AUTH_USER_MODEL)),
                ('id_persona', models.OneToOneField(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, to='lms_celestin.persona')),
            ],
            options={
                'db_table': 'administradores',
            },
        ),
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(choices=[('PADRE', 'Padre'), ('MADRE', 'Madre'), ('TUTOR', 'Tutor'), ('OTRO', 'Otro')], max_length=10)),
                ('es_principal', models.BooleanField(default=False)),
                ('es_contacto_emergencia', models.BooleanField(default=False)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acudientes', to='lms_celestin.estudiante')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acudiente_de', to='lms_celestin.persona')),
            ],
            options={
                'db_table': 'acudientes_estudiantes',
                'unique_together': {('persona', 'estudiante')},
            },
        ),
        migrations.CreateModel(
            name='AsignarAsignaturasCursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_asignatura', models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.CASCADE, to='lms_celestin.asignaturas')),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.CASCADE, to='lms_celestin.cursos')),
            ],
            options={
                'db_table': 'asignar_asignaturas_cursos',
                'unique_together': {('id_asignatura', 'id_curso')},
            },
        ),
        migrations.CreateModel(
            name='CursosDocentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.CASCADE, to='lms_celestin.cursos')),
                ('id_docente', models.ForeignKey(db_column='id_docente', on_delete=django.db.models.deletion.CASCADE, to='lms_celestin.docentes')),
            ],
            options={
                'db_table': 'cursos_docentes',
                'unique_together': {('id_curso', 'id_docente')},
            },
        ),
        migrations.CreateModel(
            name='AcudientesAlumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acudiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_celestin.acudiente')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_celestin.estudiante')),
            ],
            options={
                'db_table': 'acudientes_alumnos',
                'unique_together': {('acudiente', 'alumno')},
            },
        ),
    ]
