# Generated by Django 5.1.7 on 2025-04-15 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_celestin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administradores',
            name='password',
        ),
        migrations.AddField(
            model_name='docentes',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='administradores',
            name='id_persona',
            field=models.OneToOneField(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, to='lms_celestin.personas'),
        ),
        migrations.AlterField(
            model_name='administradores',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='id_persona',
            field=models.OneToOneField(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, to='lms_celestin.personas'),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='titulos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
