# Generated by Django 5.1.7 on 2025-03-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_celestin', '0001_initial'),
    ]

    operations = [
    ]
