# Generated by Django 5.1.7 on 2025-04-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_celestin', '0002_remove_administradores_password_docentes_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='documento',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
